CREATE USER 'qwert'@'%' IDENTIFIED BY '12345';

CREATE DATABASE IF NOT EXISTS project102;

GRANT ALL PRIVILEGES ON project102.* TO 'qwert'@'%';

FLUSH PRIVILEGES;

USE project102;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  `desc` TEXT NOT NULL,
  img VARCHAR(255) NOT NULL,
  cat VARCHAR(255) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  uid INT,
  FOREIGN KEY (uid) REFERENCES users(id)
);
